registries:
  default: https://registry.npmmirror.com/
packages:
  - "apps/*"
  - "packages/*"
  - "packages/channels/*"
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  bufferutil: false
  canvas: false
  edgedriver: false
  esbuild: true
  geckodriver: false
  msw: false
  sharp: true
  unrs-resolver: true
  utf-8-validate: false
