[package]
name = "poria-resources"
version = "0.1.0"
edition = "2021"

[dependencies]
poria-core = { path = "../poria-core" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
